maana-io/q-assistant-client

package.json
Added package.json and post-robot dependency.
=> feature/qp 35 assitant api client interface-package-json

src/AssistantAPIClient.js
Add client call for getUserInfo.
=> Add API call for getUserInfo.

src/AssistantAPIClient.js
Implement function execution eventing.
=> client-implementation-qp-161-functionExecution-eventing

src/AssistantAPIClient.js
Establish consent for notifcation, enhance add/remove, and add clearState
=> qp-224-selection-and-state

package.json
=> lock post robot version.

README.md, package.json, src/AssistantAPIClient.js
=> Feature/release v3.2.1

package.json
=> Bump develop version.

package.json
=> Bump post robot to 10.0.29

package.json, src/AssistantAPIClient.js
Merge the 3.2.2 post robot update to develop
=> Feature/develop v3.2.2

src/AssistantAPIClient.js
Initial plumbing to notify the assistant that it needs to change it render mode between background and display modes.
=> Inital implementation for render mode changed event.

src/AssistantAPIClient.js
Initial implementation of clone.
=> Initial implementation of clone.

src/AssistantAPIClient.js
This adds all the workspace functionality that the Refactor assistant should need.
=> Add the upcoming workspace functionality to the assistant API client

.prettierrc, package-lock.json, package.json
This is used to keep prettier in VSCode from changing the formatting of the file every time it is saved.
=> Add prettier to keep formatting consistent

src/AssistantAPIClient.js
forgot to add returns to my functions....
=> Fix issues with new and updated API calls

src/AssistantAPIClient.js
=> qp-792-rename-clone-to-repair

src/AssistantAPIClient.js
Also sends event data to repair event calls.
=> QP-874: Sync naming of repair with kportal.

src/AssistantAPIClient.js
Make repair and event and add reportError.
=> Qp 1256 make repair an event

src/AssistantAPIClient.js
Add API call for getAllReferencedKinds.
=> bugfix/qp-1354-Add API call for getAllReferencedKinds

README.md
=> Qp 1187 update docs v3.2.2

package-lock.json, package.json
=> Feature/version bump 3.2.3 beta

README.md
Adds the new surface area for locking to the assistant API documentation.
=> QP-787: Update the documentation for the assistant API

package-lock.json, package.json
Prepare develop for working on the 3.2.4 release
=> Feature/version bump 3.2.4 beta

package.json, src/AssistantAPIClient.js
https://maanainc.atlassian.net/browse/QP-1722
* Adds some comments to the Function functions
* Adds new functions for using service and name to load functions.
=> QP-1722: Fix part 1: Update Function functions.

package.json, src/AssistantAPIClient.js
https://maanainc.atlassian.net/browse/QP-1722
* Added some comments
* Kind of Service by Name
=> QP-1722: Part 2 Updated Kind Functionality

package-lock.json, package.json, src/AssistantAPIClient.js
https://maanainc.atlassian.net/browse/QP-1722
* Finish commenting out and cleaning up assistant API for now
Adding and removing an assistant and service.
Pulling up information about a arbitrary workspace:
=> QP-1722: Part 3: Service and Worksapce update.

package-lock.json, package.json, src/models.ts
https://maanainc.atlassian.net/browse/QP-2457
https://maanainc.atlassian.net/browse/QP-1416
https://maanainc.atlassian.net/browse/QP-2263
* Add interface for error information.
* Add moveEntities to creating a workspace.
=> QP-2257: Update models for recent changes

package-lock.json, package.json, src/models.ts
https://maanainc.atlassian.net/browse/QP-2454
* Add statusCode to the ErrorLike type.
=> QP-2454: Update Error Model.

docs/interfaces/createnodeinput.md, docs/interfaces/node.md, docs/interfaces/updatenodeinput.md, docs/interfaces/updatenodelayoutinput.md, package-lock.json, package.json, src/models.ts
https://maanainc.atlassian.net/browse/QP-2502
On nodes isCollapsed changes from a boolean to a list of string.
=> QP-2502: Handle updated isCollapsed on ndoes.

README.md, docs/README.md, docs/enums/maanaerrorcode.md, docs/interfaces/inventorychanged.md, docs/interfaces/lockchangeditem.md, docs/interfaces/lockingchanged.md, docs/modules/assistantapiclient.md, package-lock.json, package.json, src/AssistantAPIClient.ts, src/models.ts
https://maanainc.atlassian.net/browse/QP-1972
Keep all documentation on how to use the functions in the API in the documentation generated from the comments in the code.  This makes it so that it can also be seen with typescript based intellisense.
=> QP-1972: Merge Q Assistant Documentation

.github/workflows/build.yml
Allow the runner to specify which branch to publish.
Github Actions docs for `actions/checkout`: https://github.com/actions/checkout
=> Update build.yml; allow publish branch
